export interface Product {
  name: string;
  description: string;
  price: number;
  quantity: number;
  images: string[]; // เก็บอาเรย์ของ URL รูปภาพ
  type?: string; // หรือกำหนดค่า type ตามที่ UpdateProductDto ต้องการ
  details: {
    brands: '',
    warranty: '',
    dimension: '',

    series: '',
    processorNumber: '',
    socketType: '',
    coresThreads: '',
    baseFrequency: '',
    maxTurboFrequency: '',
    l2Cache: '',
    l3Cache: '',
    graphicsModels: '',
    bitSupport: '',
    cpuCooler: '',
    maximumTurboPower: '',
    
    displaySize: '',
    panelSize: '',
    resolution: '',
    resolutionType: '',
    displayColor: '',
    displayViewingArea: '',
    brightness: [''], // Initialized with an empty string for the first input
    contrastRatio: '',
    responseTime: '',
    aspectRatio: '',
    refreshRate: '',
    screenCurvature: '',
    pixelPitch: '',
    viewingAngle: '',
    colorGamut: '',
    hdrSupport: '',
    adaptiveSync: [''], // Initialized similarly
    displaySurface: '',
    flickerFree: '',
    lowBlueLight: '',
    connectivity: [''], // Initialized similarly
    signalFrequency: '',
    powerConsumption: [''], // Initialized similarly
    mechanical: [''],
    weight: [''],
    color: '',
    

    cpuSupport: '',
    cpuSocket: '',
    memorySlots: '',
    memoryType: '',
    maxMemmory: '',
    onboardGraphics: '',
    onboardAudioShipset: '',
    expansionSlots: [''],
    storage: [''],
    rearPanel: [''],
    lanChipset: '',
    lanSpeed: '',
    dimensions: '',
    powerPin: '',
    formFactor: '',
    chipset: '',
    audioChanels: ''

    gpuSeries: '',
    gpuModel: '',
    memorySize: '',
    busStandard: '',
    cudaCore: '',
    memoryInterface: '',
    boostClock: '',
    baseClock: '',
    memoryClock: '',
    maxDigitalResolution: '',
    hdmiPort: '',
    displayPort: '',
    coolerFan: '',
    powerConector: '',
    powerRequirement: '',
    
    memorySeries: '',
    memoryCapacity: '',
    casLatency: '',
    testedlatency: '',
    sdpVoltage: '',
    memoryColor: '',

    capacity: '',
    interface: '',
    readSpeed: '',
    writeSpeed: '',
    
    coolerModel: '',
    exteriorColor: '',
    cpuSocketCooler: [''],
    radiatorDimension: '',
    readiatorMeterail: '',
    radiatorSize: '',
    thermalDesignPower: '',
    pumpSpeed: '',
    fanDimensions: '',
    fanLedType: '',
    fanSpeed: '',
    fanAirflow: '',
    fanNoise: '',
    fanConnector: '',
    coolerWeight: '',
    coolerType: '',

    tiltScrollFunction: '',
    clickLifeSpan: '',
    scrollWhell: '',
    nummerOfButtons: '',
    batterryLife: '',
    batterryType: '',
    mouseInterface: '',
    sensorResolution: '',
    sensorTechnology: '',
    wirelessTechnology: '',

    switchName: '',
    keyboardConnectivity: '',
    lighting: '',
    localization: '',
    materail: '',
    wirelessFrequency: '',
    batteryTypeAndQuantity: '',
    keyboardWeight: '',
    usbPort: '',
    type: '',
    wiredOrWireless: '',

    connector: '',
    driverUnit: '',
    frequencyResponse: '',
    sensitivity: '',
    inputImpedance: '',
    micFrequencyResponse: '',
    micSensitivity: '',
    micImpedance: '',
    cordLenght: '',

    energyEfficient: '',
    modular: '',
    continuousPowerW: '',
    psuFormFactor: '',
    mbConnector: '',
    cpuConnector: '',
    pcieConnector: [''],
    sataConnector: '',
    fanSize: '',
    psuWeight: '',
    protection: '',
    powerRage: '',

    model: '',
    mainboardSupport: [''],
    vgaSupport: '',
    cpuCoolerSupport: '',
    powerSupplySupport: '',
    frontIO: '',
    caseExpansionSlots: '',
    driveBaysSupport: '',
    fanInstallment: '',
    fanSupportFront: '',
    fanSupportTop: '',
    fanSupportSide: '',
    fanSupportRear: '',
    fanSupportBottom: '',
    maxRadiatorSupport: '',
    radidatorSupportFront: '',
    radiatorSupportTop: '',
    radiatoSupportSide: '',
    radiatorSupportRear: '',
    radiatorSupportBottom: '',
    accessories: '',
    caseWeight: '',
  }
}
